name: Build Files (Fork)
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  WORKING_DIR: ${{ github.workspace }}
  SOLUTION_PATH: '${{ github.workspace }}\Files.slnx'
  APP_PROJECT_PATH: '${{ github.workspace }}\src\Files.App\Files.App.csproj'
  APPX_PACKAGE_DIR: '${{ github.workspace }}\artifacts\AppxPackages\'
  APPX_SELFSIGNED_CERT_PATH: '${{ github.workspace }}\.github\workflows\FilesApp_SelfSigned.pfx'
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      ARCHITECTURE: ${{ matrix.platform }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore Files
      shell: pwsh
      run: |
        msbuild $env:SOLUTION_PATH `
          -t:Restore `
          -p:Platform=$env:ARCHITECTURE `
          -p:Configuration=$env:CONFIGURATION `
          -p:PublishReadyToRun=true `
          -v:quiet
    - name: Create self signed cert as a pfx file
      run: ./.github/scripts/Generate-SelfCertPfx.ps1 -Destination "$env:APPX_SELFSIGNED_CERT_PATH"
    - name: Build & package Files
      run: |
        msbuild `
          $env:APP_PROJECT_PATH `
          -t:Build `
          -p:Configuration=$env:CONFIGURATION `
          -p:Platform=$env:ARCHITECTURE `
          -p:AppxBundlePlatforms=$env:ARCHITECTURE `
          -p:AppxBundle=Always `
          -p:GenerateAppxPackageOnBuild=true `
          -p:UapAppxPackageBuildMode=SideloadOnly `
          -p:AppxPackageDir=$env:APPX_PACKAGE_DIR `
          -p:AppxPackageSigningEnabled=true `
          -p:PackageCertificateKeyFile=$env:APPX_SELFSIGNED_CERT_PATH `
          -p:PackageCertificatePassword="" `
          -p:PackageCertificateThumbprint="" `
          -v:quiet
    - name: Upload AppX Package
      uses: actions/upload-artifact@v4
      with:
        name: 'Files-AppxPackage-${{ env.CONFIGURATION }}-${{ env.ARCHITECTURE }}'
        path: ${{ env.APPX_PACKAGE_DIR }}
        retention-days: 7
